# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy container app to Azure Web App - PyResourceOptimizer

on:
  push:
    branches:
      - deploy
  workflow_dispatch:

jobs:
  build:
    runs-on: 'ubuntu-latest'

    steps:
    - uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to registry
      uses: docker/login-action@v1
      with:
        registry: https://pyopapp2registry.azurecr.io/
        username: ${{ secrets.AzureAppService_ContainerUsername_7a0cc1b7183a48f096c0f66d7ef0635b }}
        password: ${{ secrets.AzureAppService_ContainerPassword_1414be6e2a254f6dad041f895263fcd8 }}

    - name: Build and push container image to registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: pyopapp2registry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7a0cc1b7183a48f096c0f66d7ef0635b }}/pyop-app:${{ github.sha }}
        file: ./Dockerfile

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
    - name: Deploy to Azure Web App
      id: deploy-to-webapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'PyResourceOptimizer'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_9d61910ab0bf4fd3b93224114737390b }}
        images: 'pyopapp2registry.azurecr.io/${{ secrets.AzureAppService_ContainerUsername_7a0cc1b7183a48f096c0f66d7ef0635b }}/pyop-app:${{ github.sha }}'